Avasam:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
BenjaminSchubert:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
BoWuGit:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
CarstenGrohmann:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
Cheukting:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
DetachHead:
  code: 0.55
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
HomieOmie:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
JamieC2002:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
Leithal3:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
MarcBresson:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
OlegP-andrew:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
Pierre-Sassoulas:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
PrastianHD:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
RonnyPfannschmidt:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
SharadNair7:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
ShurikMen:
  code: 0.65
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.3
  task_types:
  - 0
  - 0
  - 0
Songpeng-ANU:
  code: 0.15
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
SongpengLiu:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
StarryZhang-whu:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
Sveimoldr:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
TanyaAgarwal28:
  code: 0.95
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
The-Compiler:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
Tusenka:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.4
  task_types:
  - 0
  - 0
  - 0
TyYan03:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
WarrenTheRabbit:
  code: 0.9
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.4
  task_types:
  - 0
  - 0
  - 0
Zac-HD:
  code: 0.5
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
adamjstewart:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
agronholm:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
akhilramkee:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
aless10:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
andresliszt:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
antosikv:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
ardavan34:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
arthuRHD:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
asottile:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.35
  task_types:
  - 0
  - 0
  - 0
avshisnyk:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
bastimeyer:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
bbrown1867:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
bluetech:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
bnomis:
  code: 0.45
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
brl0:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
bsour:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
bukzor:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
bzoracler:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
calestyo:
  code: 0.6
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
cdce8p:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.45
  task_types:
  - 0
  - 0
  - 0
chrimaho:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
cielavenir:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
cj-timothy-sampson:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
clee2000:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
dheerajck:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
dhruvk12:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
donhui:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
dqkqd:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
edgarrmondragon:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
eerovaher:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
erik-hasse:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
etianen:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
facundobatista:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
faisal-fawad:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
faph:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
fcharras:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
ferdnyc:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
flying-sheep:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.25
  task_types:
  - 0
  - 0
  - 0
fraserstark:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
fruch:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.3
  task_types:
  - 0
  - 0
  - 0
github-actions:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
glemaitre:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
graingert:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
hroncok:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
hugovk:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
ihindi1111:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
ivirshup:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
jack-zj-liu:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
jakkdl:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
jaraco:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
jenstroeger:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
jgersti:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
jkeifer:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
jobh:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
jparise:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
jsoref:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
kenny-y-dev:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
krassowski:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
lanzz:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
larsoner:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
leeyueh:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
lesnek:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.35
  task_types:
  - 0
  - 0
  - 0
lesteve:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.25
  task_types:
  - 0
  - 0
  - 0
levsa:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
mgorny:
  code: 0.45
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
morty:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
mrbean-bremen:
  code: 0.35
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0
mthaitan:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
neilmartin2000:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
neutrinoceros:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
nicoddemus:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
ntjohnson1:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
okken:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.25
  task_types:
  - 0
  - 0
  - 0
palonza:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
phamvanhan68:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
plannigan:
  code: 0.35
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.55
  task_types:
  - 0
  - 0
  - 0
pllim:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
pomponchik:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
pre-commit-ci:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
pyuscherbakov:
  code: 0.1
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
reaganjlee:
  code: 0.6
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.4
  task_types:
  - 0
  - 0
  - 0
rmartin16:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
roberto-aldera:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.35
  task_types:
  - 0
  - 0
  - 0
ryanpudd:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
sadra-barikbin:
  code: 1.0
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 1.0
  task_types:
  - 0
  - 0
  - 0
scop:
  code: 0.5
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
seanjedi:
  code: 0.6
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.45
  task_types:
  - 0
  - 0
  - 0
seanpourgoutzidis:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
soxofaan:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
stoeckmann:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
sturmf:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
tamird:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.45
  task_types:
  - 0
  - 0
  - 0
theirix:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
tjsmart:
  code: 0.4
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.3
  task_types:
  - 0
  - 0
  - 0
touilleWoman:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
tserg:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
tushar-deepsource:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
ubaumann:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
udaymankena:
  code: 0.2
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
webknjaz:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
whysage:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.3
  task_types:
  - 0
  - 0
  - 0
woutdenolf:
  code: 0.35
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.15
  task_types:
  - 0
  - 0
  - 0
zhangwk02:
  code: 0.25
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
ziad-kermadi:
  code: 0.15
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.1
  task_types:
  - 0
  - 0
  - 0
ziadk:
  code: 0.3
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  review: 0.2
  task_types:
  - 0
  - 0
  - 0

dependabot:
  lang_emb: [1.0, 0.0, 0.0]
  skill:
    code: 0.5
    review: 0.3
  task_types: [0, 0, 0]

robotherapist:
  lang_emb: [1.0, 0.0, 0.0]
  skill:
    code: 0.5
    review: 0.3
  task_types: [0, 0, 0]
