01DarshanPatni:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.68
    review: 0.82
  task_types:
  - 1
  - 3
  - 4
40gilad:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.8
    review: 0.89
  task_types:
  - 2
  - 5
  - 4
Akshay9715:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.78
    review: 0.66
  task_types:
  - 2
  - 5
  - 5
AluminumAngel:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.67
    review: 0.46
  task_types:
  - 3
  - 5
  - 2
Arbmani:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.49
    review: 0.56
  task_types:
  - 3
  - 1
  - 5
CatarinaPBressan:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.48
    review: 0.52
  task_types:
  - 2
  - 5
  - 5
CheeseCake87:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.57
    review: 0.72
  task_types:
  - 1
  - 4
  - 5
ComputerScienceGirl12:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.58
    review: 0.98
  task_types:
  - 3
  - 2
  - 1
CoolCat467:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.49
    review: 0.65
  task_types:
  - 3
  - 4
  - 1
EdgarPrueba:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.78
    review: 0.31
  task_types:
  - 1
  - 5
  - 3
Gable-github:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.81
    review: 0.95
  task_types:
  - 1
  - 1
  - 4
HackingGate:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.57
    review: 0.76
  task_types:
  - 2
  - 5
  - 2
JannesvandenBogert:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.8
    review: 0.71
  task_types:
  - 1
  - 3
  - 5
Josecespedesant:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.76
    review: 0.78
  task_types:
  - 5
  - 2
  - 5
Kartikeya-Kotkar:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.76
    review: 0.5
  task_types:
  - 5
  - 5
  - 2
MayureshMore:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.31
    review: 0.94
  task_types:
  - 1
  - 3
  - 5
Merida39:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.63
    review: 0.8
  task_types:
  - 1
  - 1
  - 5
RonnyPfannschmidt:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.86
    review: 0.82
  task_types:
  - 5
  - 3
  - 4
ThiefMaster:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.81
    review: 0.59
  task_types:
  - 2
  - 3
  - 5
ThisIzAli2:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.81
    review: 0.98
  task_types:
  - 3
  - 2
  - 5
Vrusharth:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.69
    review: 0.4
  task_types:
  - 3
  - 2
  - 5
Wiczka03:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.92
    review: 0.45
  task_types:
  - 5
  - 5
  - 2
Wowieee4:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.47
    review: 0.43
  task_types:
  - 1
  - 2
  - 5
Zephyr0071:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.63
    review: 0.55
  task_types:
  - 4
  - 5
  - 1
abhiramk6:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.34
    review: 0.44
  task_types:
  - 5
  - 2
  - 2
amrear:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.96
    review: 0.83
  task_types:
  - 5
  - 2
  - 5
ascender1729:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.36
    review: 0.5
  task_types:
  - 2
  - 5
  - 2
aswindevsp:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.88
    review: 0.97
  task_types:
  - 1
  - 1
  - 3
ayushjain01:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.39
    review: 0.52
  task_types:
  - 5
  - 2
  - 5
brendon-codes:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.98
  task_types:
  - 1
  - 4
  - 5
cdce8p:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.98
    review: 0.53
  task_types:
  - 2
  - 5
  - 2
chakib401:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.55
    review: 0.68
  task_types:
  - 3
  - 1
  - 2
cureprotocols:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.52
    review: 0.96
  task_types:
  - 5
  - 5
  - 3
danielvdao:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.77
    review: 0.83
  task_types:
  - 4
  - 4
  - 1
davidism:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.67
    review: 0.49
  task_types:
  - 1
  - 3
  - 4
degerahmet:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.66
    review: 0.57
  task_types:
  - 2
  - 1
  - 1
dependabot:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.38
    review: 0.58
  task_types:
  - 3
  - 4
  - 2
differencialx:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.32
    review: 0.82
  task_types:
  - 1
  - 4
  - 2
dunkmann00:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.33
    review: 0.79
  task_types:
  - 3
  - 4
  - 4
gaburn:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.77
    review: 0.51
  task_types:
  - 2
  - 2
  - 2
girishonweb:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.97
    review: 0.74
  task_types:
  - 2
  - 2
  - 5
greyli:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.64
  task_types:
  - 1
  - 3
  - 4
hatmic0101:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.57
    review: 0.32
  task_types:
  - 3
  - 1
  - 3
jalaj711:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.57
    review: 0.4
  task_types:
  - 3
  - 2
  - 4
kadai0308:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.65
    review: 0.65
  task_types:
  - 4
  - 4
  - 5
kavasg:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.98
    review: 0.47
  task_types:
  - 1
  - 3
  - 1
kotvkvante:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.7
    review: 0.55
  task_types:
  - 1
  - 5
  - 4
kurtatter:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.46
    review: 0.9
  task_types:
  - 5
  - 3
  - 5
kurtmckee:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.5
    review: 0.4
  task_types:
  - 4
  - 4
  - 1
markparonyan:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.34
    review: 0.68
  task_types:
  - 5
  - 2
  - 5
moon548834:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.49
    review: 0.97
  task_types:
  - 1
  - 3
  - 3
najasnake12:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.5
    review: 0.65
  task_types:
  - 2
  - 4
  - 2
palako:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.49
  task_types:
  - 3
  - 5
  - 4
pamelafox:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.83
  task_types:
  - 4
  - 5
  - 1
pgjones:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.74
  task_types:
  - 1
  - 3
  - 4
pre-commit-ci:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.76
    review: 0.75
  task_types:
  - 3
  - 3
  - 4
ranveer9:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.5
    review: 0.97
  task_types:
  - 3
  - 4
  - 1
s-hamann:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.76
    review: 0.9
  task_types:
  - 1
  - 1
  - 3
samuelpondugala:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.54
  task_types:
  - 5
  - 4
  - 5
sanjaytaylor2012:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.92
    review: 0.72
  task_types:
  - 3
  - 5
  - 3
strugee:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.55
    review: 0.79
  task_types:
  - 4
  - 4
  - 2
tomasz-pankowski:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.68
    review: 0.74
  task_types:
  - 4
  - 2
  - 5
zhuangzhuang:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.68
    review: 0.91
  task_types:
  - 3
  - 1
  - 3
