Avasam:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
BenjaminSchubert:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.7
    review: 0.45
  task_types:
  - 0
  - 0
  - 0
BoWuGit:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
CarstenGrohmann:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
Cheukting:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
DetachHead:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
Leithal3:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
MarcBresson:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
Pierre-Sassoulas:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.77
    review: 1.0
  task_types:
  - 0
  - 0
  - 0
RonnyPfannschmidt:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.64
    review: 1.0
  task_types:
  - 0
  - 0
  - 0
SharadNair7:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
ShurikMen:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
StarryZhang-whu:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
TanyaAgarwal28:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
The-Compiler:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.75
    review: 0.97
  task_types:
  - 0
  - 0
  - 0
Tusenka:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.56
  task_types:
  - 0
  - 0
  - 0
WarrenTheRabbit:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.6
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
Zac-HD:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.92
  task_types:
  - 0
  - 0
  - 0
adamjstewart:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
akhilramkee:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
aless10:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
antosikv:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
arthuRHD:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
asottile:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.6
  task_types:
  - 0
  - 0
  - 0
bastimeyer:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
bbrown1867:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
bluetech:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 1.0
    review: 1.0
  task_types:
  - 0
  - 0
  - 0
bnomis:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
brl0:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
bsour:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
bzoracler:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
calestyo:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.56
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
cdce8p:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
chrimaho:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
cielavenir:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
clee2000:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
dependabot:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 1.0
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
dheerajck:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
dhruvk12:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.45
  task_types:
  - 0
  - 0
  - 0
donhui:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
dqkqd:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
eerovaher:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
erik-hasse:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
etianen:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
facundobatista:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
faisal-fawad:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
faph:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
fcharras:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
fraserstark:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
fruch:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
github-actions:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 1.0
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
glemaitre:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
hroncok:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
hugovk:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
ivirshup:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
jakkdl:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.64
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
jaraco:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.51
  task_types:
  - 0
  - 0
  - 0
jenstroeger:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
jkeifer:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
jobh:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
jparise:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
jsoref:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
kenny-y-dev:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
lanzz:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
larsoner:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
leeyueh:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
lesnek:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
lesteve:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
levsa:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
mgorny:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
morty:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
mrbean-bremen:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
neilmartin2000:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
neutrinoceros:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
nicoddemus:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 1.0
    review: 1.0
  task_types:
  - 0
  - 0
  - 0
phamvanhan68:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
plannigan:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
pllim:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.45
  task_types:
  - 0
  - 0
  - 0
pomponchik:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
pre-commit-ci:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 1.0
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
pyuscherbakov:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.45
  task_types:
  - 0
  - 0
  - 0
reaganjlee:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
rmartin16:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
roberto-aldera:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
ryanpudd:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
sadra-barikbin:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.56
    review: 0.45
  task_types:
  - 0
  - 0
  - 0
scop:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
seanjedi:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
soxofaan:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
stoeckmann:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
sturmf:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
tamird:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
theirix:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
tjsmart:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.51
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
touilleWoman:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
tserg:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
tushar-deepsource:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
ubaumann:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
udaymankena:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
webknjaz:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.3
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
whysage:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
woutdenolf:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
ziadk:
  lang_emb:
  - 1.0
  - 0.0
  - 0.0
  skill:
    code: 0.45
    review: 0.3
  task_types:
  - 0
  - 0
  - 0
